### ISSUE TITLE
Cannot read property 'requires' of undefined

### ISSUE THREAD

**Issue by jdmarshall** [amio/npm-why#100]
Fresh install under node 10.17.0, this occurs with a global or a local install:

```
  Object.keys(lockNode.requires || {}).forEach(name => {
                       ^

TypeError: Cannot read property 'requires' of undefined
    at addChild (/usr/local/lib/node_modules/npm-why/node_modules/npm-logical-tree/index.js:128:24)
    at Array.from.forEach.name (/usr/local/lib/node_modules/npm-why/node_modules/npm-logical-tree/index.js:113:5)
    at Array.forEach (<anonymous>)
    at lockTree (/usr/local/lib/node_modules/npm-why/node_modules/npm-logical-tree/index.js:107:5)
    at module.exports (/usr/local/lib/node_modules/npm-why/index.js:11:16)
    at main (/usr/local/lib/node_modules/npm-why/cli-main.js:12:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-why/bin/npm-why:39:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by amio** [comment]
Hi @jdmarshall, can I have look at your `package.json` and `package-lock.json`?

**Comment by VladimirHumeniuk** [comment]
same error for me

**Comment by jdmarshall** [comment]
Don't think I can share that (corporate).  It's nothing straightforward, no problem with some 3rd party code.  I'll check a few other projects I have floating about and see if I can find the common thread.
