### ISSUE TITLE
Error: loadVirtual requires existing shrinkwrap file

### ISSUE THREAD

**Issue by stevobm** [amio/npm-why#176]
When I run `npx npm-why babel-core`, something wrong happened(node v12.18.1):
(node:12148) UnhandledPromiseRejectionWarning: Error: loadVirtual requires existing shrinkwrap file
    at Arborist.loadVirtual (/Users/vo/.npm/_npx/12148/lib/node_modules/npm-why/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:57:18)
    at async collectReasons (/Users/vo/.npm/_npx/12148/lib/node_modules/npm-why/index.js:31:16)
    at async main (/Users/vo/.npm/_npx/12148/lib/node_modules/npm-why/index.js:12:19)
(node:12148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12148) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by universalhandle** [comment]
I think what's happened here is that you ran the command in a directory which does not have a package.json file. Older versions seem to handle this better. For node v10.16.3, npm-why 1.1.8, I get:

```bash
$ npm-why someModule

  ERROR Cannot find package.json.
```

With node v14.16.0, npm-why 2.1.3, I get a similar result to yours.
